/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interface;

import Model.LetraNumerico;
import Model.Soletra;
import Model.Sonumeros;
import Persistencia.ControlaCliente;
import controle.Cliente;
import controle.Projeto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author iiury
 */
public class jifcadastro extends javax.swing.JInternalFrame {

    /**
     * Creates new form jifcadastro
     */
    int auxiliar = 0;//variável pra ajudar a descidir se é novo ou editar
    int aux_limp = 0;//variavelauxiliar para zerar campos
    public jifcadastro() {
        initComponents();
        //restringindo o teclado aos campos referentes
        txtnome.setDocument(new Soletra());
        txtcpf.setDocument(new Sonumeros());
        txttelefone.setDocument(new Sonumeros());
        txtvalorprojeto.setDocument(new Sonumeros());
        txtprojeto.setDocument(new LetraNumerico());
        txtdescricaoprojeto.setDocument(new LetraNumerico());
        //ativando o radio
        rativo.isSelected();
        //desabilitando os campos e botões
        btnovo.setEnabled(false);
        btexcluir.setEnabled(false);
        bteditar.setEnabled(false);
        txtnome.setEnabled(false);
        spinidade.setEnabled(false);
        txtcpf.setEnabled(false);
        txttelefone.setEnabled(false);
        rativo.setEnabled(false);
        rinativo.setEnabled(false);
        txtprojeto.setEnabled(false);
        txtvalorprojeto.setEnabled(false);
        txtdescricaoprojeto.setEnabled(false); 
        btnovo.setEnabled(true);
        btexcluir.setEnabled(false);
        bteditar.setEnabled(false);
        btsalvar.setEnabled(false);
    }
    public void mostrarcliente(){
        ArrayList<Cliente> clientes = Principal.c.retornarTodos();
        DefaultTableModel modelo = (DefaultTableModel) tblcliente.getModel();
        //determinando o numero de linhas
        modelo.setNumRows(clientes.size());
        //mostrando os clientes
        for (int i = 0; i < clientes.size() && clientes.get(i) != null ; i++) {
            tblcliente.setValueAt(clientes.get(i).getNome(), i, 0);
            tblcliente.setValueAt(clientes.get(i).getCpf(), i, 1);
            tblcliente.setValueAt(clientes.get(i).getIdade(), i, 2);
            tblcliente.setValueAt(clientes.get(i).getTelefone(), i, 3);
            tblcliente.setValueAt(clientes.get(i).getProjeto().getNome(), i, 4);
            tblcliente.setValueAt(clientes.get(i).getProjeto().getValor(), i, 5);
            tblcliente.setValueAt(clientes.get(i).getProjeto().getDescricao(), i, 6);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        dadosprojeto = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtprojeto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtvalorprojeto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdescricaoprojeto = new javax.swing.JTextArea();
        dadospessoais = new javax.swing.JPanel();
        txtnome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spinidade = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        txtcpf = new javax.swing.JTextField();
        txttelefone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rativo = new javax.swing.JRadioButton();
        rinativo = new javax.swing.JRadioButton();
        btlimpar3 = new javax.swing.JButton();
        btsalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcliente = new javax.swing.JTable();
        bteditar = new javax.swing.JButton();
        btexcluir = new javax.swing.JButton();
        btnovo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        dadosprojeto.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.darkGray));
        dadosprojeto.setToolTipText("Dados do Projeto");
        dadosprojeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dadosprojetoMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Nome do Projeto:");

        txtprojeto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Valor do Projeto:");

        txtvalorprojeto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Descrição do Projeto:");

        txtdescricaoprojeto.setColumns(20);
        txtdescricaoprojeto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtdescricaoprojeto.setRows(5);
        jScrollPane2.setViewportView(txtdescricaoprojeto);

        javax.swing.GroupLayout dadosprojetoLayout = new javax.swing.GroupLayout(dadosprojeto);
        dadosprojeto.setLayout(dadosprojetoLayout);
        dadosprojetoLayout.setHorizontalGroup(
            dadosprojetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosprojetoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dadosprojetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(dadosprojetoLayout.createSequentialGroup()
                        .addComponent(txtprojeto, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtvalorprojeto))
                    .addGroup(dadosprojetoLayout.createSequentialGroup()
                        .addGroup(dadosprojetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dadosprojetoLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(167, 167, 167)
                                .addComponent(jLabel13))
                            .addComponent(jLabel14))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dadosprojetoLayout.setVerticalGroup(
            dadosprojetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosprojetoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dadosprojetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosprojetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprojeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtvalorprojeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dadospessoais.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.darkGray));
        dadospessoais.setToolTipText("Dados Pessoais");
        dadospessoais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dadospessoaisMouseClicked(evt);
            }
        });

        txtnome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomeKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Idade:");

        spinidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        spinidade.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spinidade.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("CPF:");

        txtcpf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txttelefone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Telefone:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Status:");

        buttonGroup1.add(rativo);
        rativo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rativo.setSelected(true);
        rativo.setText("Ativo");

        buttonGroup1.add(rinativo);
        rinativo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rinativo.setText("Inativo");

        javax.swing.GroupLayout dadospessoaisLayout = new javax.swing.GroupLayout(dadospessoais);
        dadospessoais.setLayout(dadospessoaisLayout);
        dadospessoaisLayout.setHorizontalGroup(
            dadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadospessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dadospessoaisLayout.createSequentialGroup()
                        .addGroup(dadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dadospessoaisLayout.createSequentialGroup()
                                .addGroup(dadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dadospessoaisLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(0, 319, Short.MAX_VALUE))
                                    .addComponent(txtnome))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spinidade, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addGroup(dadospessoaisLayout.createSequentialGroup()
                                .addComponent(txtcpf, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(dadospessoaisLayout.createSequentialGroup()
                        .addGroup(dadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(dadospessoaisLayout.createSequentialGroup()
                                .addComponent(rativo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rinativo)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dadospessoaisLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(145, 145, 145))))
        );
        dadospessoaisLayout.setVerticalGroup(
            dadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadospessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rativo)
                    .addComponent(rinativo))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btlimpar3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btlimpar3.setForeground(new java.awt.Color(102, 0, 0));
        btlimpar3.setText("Limpar");
        btlimpar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlimpar3ActionPerformed(evt);
            }
        });

        btsalvar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btsalvar.setForeground(new java.awt.Color(0, 102, 51));
        btsalvar.setText("Salvar");
        btsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvarActionPerformed(evt);
            }
        });

        tblcliente.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblcliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NOME", "CPF", "IDADE", "TELEFONE", "PROJETO", "VALOR", "DESCRIÇÃO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblcliente.setToolTipText("");
        tblcliente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tblclienteMouseMoved(evt);
            }
        });
        tblcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblclienteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tblclienteMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(tblcliente);

        bteditar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bteditar.setForeground(new java.awt.Color(153, 153, 0));
        bteditar.setText("Editar");
        bteditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditarActionPerformed(evt);
            }
        });

        btexcluir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btexcluir.setForeground(new java.awt.Color(153, 0, 0));
        btexcluir.setText("Excluir");
        btexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexcluirActionPerformed(evt);
            }
        });

        btnovo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnovo.setForeground(new java.awt.Color(0, 0, 102));
        btnovo.setText("Novo");
        btnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dadospessoais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dadosprojeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btlimpar3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bteditar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dadospessoais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dadosprojeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btlimpar3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bteditar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(375, 25, 1196, 579);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomeKeyPressed

    }//GEN-LAST:event_txtnomeKeyPressed

    private void btlimpar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlimpar3ActionPerformed
        txtnome.setText("");
        spinidade.setValue(0);
        txtcpf.setText("");
        txttelefone.setText("");
        rativo.setSelected(false);
        rinativo.setSelected(false);
        txtprojeto.setText("");
        txtvalorprojeto.setText("");
        txtdescricaoprojeto.setText("");
        JOptionPane.showMessageDialog(null, "Campos Apagados!");
    }//GEN-LAST:event_btlimpar3ActionPerformed

    private void btsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvarActionPerformed
        if(txtnome.getText().length()==0||txtcpf.getText().length()==0||txtprojeto.getText().length()==0||txtvalorprojeto.getText().length()==0||txtdescricaoprojeto.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Preencha todos os Campos!");
        }else if(txtcpf.getText().length()<11||txtcpf.getText().length()>11){
            JOptionPane.showMessageDialog(null, "CPF inválido!!!");
        }else if(txttelefone.getText().length()<11||txttelefone.getText().length()>11){
            JOptionPane.showMessageDialog(null, "Telefone inválido para o Brasil!!!\nUse o padrão: ' (xx)xxxx-xxxx '  ");
        }else{
            if(auxiliar==0){
                //instanciando o projeto
                Projeto projeto = new Projeto();
                projeto.setNome(txtprojeto.getText().trim());
                projeto.setValor(Double.parseDouble(txtvalorprojeto.getText().trim()));
                projeto.setDescricao(txtdescricaoprojeto.getText().trim());
                //intanciando o cliente
                Cliente cliente = new Cliente();
                cliente.setNome(txtnome.getText().trim());
                cliente.setCpf(txtcpf.getText().trim());
                cliente.setTelefone(txttelefone.getText().trim());
                cliente.setIdade(spinidade.getValue().toString());
                if(rativo.isSelected()==true){
                    cliente.setStatus('a');

                }else{
                    cliente.setStatus('i');
                }
                cliente.setProjeto(projeto);
                //tentar salvar
                if(Principal.c.salvar(cliente)){
                    JOptionPane.showMessageDialog(null, "Cliente Cadastrado!");
                    //limpado os campos pro próximo cadastro
                    txtnome.setText("");
                    spinidade.setValue(0);
                    txtcpf.setText("");
                    txttelefone.setText("");
                    rativo.setSelected(false);
                    rinativo.setSelected(false);
                    txtprojeto.setText("");
                    txtvalorprojeto.setText("");
                    txtdescricaoprojeto.setText("");
                    txtnome.requestFocus();
                    //atualizando a tabela
                    mostrarcliente();
                }else{
                    JOptionPane.showMessageDialog(null, "Erro no cadastro desse cliente !!!");
                }
            }else if(auxiliar==1){
                //variavel auxiliar de arrays e posição
                ArrayList<Cliente> clientes = Principal.c.retornarTodos();
                int posicao = tblcliente.getSelectedRow();
                //atualizando os dados
                clientes.get(posicao).setNome(txtnome.getText());
                clientes.get(posicao).setIdade(spinidade.getValue().toString());
                clientes.get(posicao).setCpf(txtcpf.getText());
                clientes.get(posicao).setTelefone(txttelefone.getText());
                if(rativo.isSelected()==true){
                   clientes.get(posicao).setStatus('a'); 
                }else{
                    clientes.get(posicao).setStatus('i');
                }
                //nova variavel de projeto para auxiliar a atulização
                Projeto projeto = new Projeto(txtprojeto.getText(), txtdescricaoprojeto.getText(), Double.parseDouble(txtvalorprojeto.getText()));
                clientes.get(posicao).setProjeto(projeto);
                //atualizando a tabela
                mostrarcliente();
            }else{
                JOptionPane.showMessageDialog(null, "Erro ao executar esta ação");
            }
            
            //desabilitando os campos e botoes
            btnovo.setEnabled(true);
            btsalvar.setEnabled(false);
            btexcluir.setEnabled(false);
            bteditar.setEnabled(false);
            txtnome.setEnabled(false);
            spinidade.setEnabled(false);
            txtcpf.setEnabled(false);
            txttelefone.setEnabled(false);
            rativo.setEnabled(false);
            rinativo.setEnabled(false);
            txtprojeto.setEnabled(false);
            txtvalorprojeto.setEnabled(false);
            txtdescricaoprojeto.setEnabled(false);
            
        }
    }//GEN-LAST:event_btsalvarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        Principal.naTela = false;
    }//GEN-LAST:event_formInternalFrameClosed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        mostrarcliente();
    }//GEN-LAST:event_formInternalFrameOpened

    private void bteditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditarActionPerformed
        ArrayList<Cliente> clientes = Principal.c.retornarTodos();
        //verificando se há conteudo na tabela
        if(clientes.size()>0){
            //verificando se selecionou lnha
            if(tblcliente.getSelectedRow()>=0){
                //recebendo a confirmação
                int conf = JOptionPane.showConfirmDialog(null, "Certeza que deseja EDITAR o cadastro de "+clientes.get(tblcliente.getSelectedRow()).getNome()+" ? ", "EXCLUSÃO", WIDTH, HEIGHT, null);
                //editando a linha selecionada
                if(conf==0){
                    //variavel auxiliar recebe 1 referente a editar
                    auxiliar=1; 
                    //habilitando os campos e os botoes
                    txtnome.setEnabled(true);
                    spinidade.setEnabled(true);
                    txtcpf.setEnabled(true);
                    txttelefone.setEnabled(true);
                    rativo.setEnabled(true);
                    rinativo.setEnabled(true);
                    txtprojeto.setEnabled(true);
                    txtvalorprojeto.setEnabled(true);
                    txtdescricaoprojeto.setEnabled(true); 
                    btsalvar.setEnabled(true);
                    btexcluir.setEnabled(false);
                    bteditar.setEnabled(false);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Para excluir, primeiro selecione a linha correspondente ao Cliente!");
            }
        }else{
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO POSSUI CLIENTES !!!\n Cadastre alguns para poder editar");
        }
    }//GEN-LAST:event_bteditarActionPerformed

    private void btexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexcluirActionPerformed
        ArrayList<Cliente> clientes = Principal.c.retornarTodos();
        //verificando se há conteudo na tabela
        if(clientes.size()>0){
            //verificando se selecionou lnha
            if(tblcliente.getSelectedRow()>=0){
                //recebendo a confirmação
                int conf = JOptionPane.showConfirmDialog(null, "Certeza que deseja excluir "+clientes.get(tblcliente.getSelectedRow()).getNome()+" de sua lista de Clientes? ", "EXCLUSÃO", WIDTH, HEIGHT, null);
                //excluindo a linha selecionada
                if(conf==0){
                    //limpado os campos pro próximo cadastro
                    txtnome.setText("");
                    spinidade.setValue(0);
                    txtcpf.setText("");
                    txttelefone.setText("");
                    rativo.setSelected(false);
                    rinativo.setSelected(false);
                    txtprojeto.setText("");
                    txtvalorprojeto.setText("");
                    txtdescricaoprojeto.setText("");
                    if(Principal.c.excluir(clientes.get(tblcliente.getSelectedRow()))){
                        JOptionPane.showMessageDialog(null, "APAGADO COM SUCESSO");
                        //atualizando tabela
                        mostrarcliente();
                    }else{
                        JOptionPane.showMessageDialog(null, "erro ao apagar !");
                    }
                    if(clientes.get(tblcliente.getSelectedRow()).getNome().length()<1){
                        JOptionPane.showMessageDialog(null, "tem nada aqui ");
                    }
                    
                }   
            }else{
                JOptionPane.showMessageDialog(null, "Para excluir, primeiro selecione a linha correspondente ao Cliente!");
            }   
        }else{
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO POSSUI CLIENTES !!!\n Cadastre alguns para poder excluir");
        }
        
    }//GEN-LAST:event_btexcluirActionPerformed

    private void tblclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblclienteMouseClicked
        ArrayList<Cliente> clientes = Principal.c.retornarTodos();
        //verificando se há conteudo na tabela
        if(clientes.size()>0){
            //verificando se selecionou lnha
            if(tblcliente.getSelectedRow()>=0){
                //exibindo os dados nos campos
                txtnome.setText(clientes.get(tblcliente.getSelectedRow()).getNome());
                spinidade.setValue(Integer.parseInt(clientes.get(tblcliente.getSelectedRow()).getIdade()));
                txtcpf.setText(clientes.get(tblcliente.getSelectedRow()).getCpf());
                txttelefone.setText(clientes.get(tblcliente.getSelectedRow()).getTelefone());
                if(clientes.get(tblcliente.getSelectedRow()).getStatus()=="Desativado"){
                    rinativo.isSelected();
                    rinativo.setSelected(true);
                }else{
                    rativo.setSelected(true);
                }
                txtprojeto.setText(clientes.get(tblcliente.getSelectedRow()).getProjeto().getNome());
                txtvalorprojeto.setText(tblcliente.getValueAt(tblcliente.getSelectedRow(), 5).toString());
                txtdescricaoprojeto.setText(clientes.get(tblcliente.getSelectedRow()).getProjeto().getDescricao());
                //desabilitando os campos
                txtnome.setEnabled(false);
                spinidade.setEnabled(false);
                txtcpf.setEnabled(false);
                txttelefone.setEnabled(false);
                rativo.setEnabled(false);
                rinativo.setEnabled(false);
                txtprojeto.setEnabled(false);
                txtvalorprojeto.setEnabled(false);
                txtdescricaoprojeto.setEnabled(false);   
                btexcluir.setEnabled(true);
                bteditar.setEnabled(true);
                btnovo.setEnabled(false);
            }else{
                JOptionPane.showMessageDialog(null, "Para vizualizar, primeiro selecione a linha correspondente ao Cliente!");
            }  
        }else{
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO POSSUI CLIENTES !!!");
        }
        
    }//GEN-LAST:event_tblclienteMouseClicked

    private void btnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnovoActionPerformed
        //limpado os campos pro próximo cadastro
        txtnome.setText("");
        spinidade.setValue(0);
        txtcpf.setText("");
        txttelefone.setText("");
        rativo.setSelected(false);
        rinativo.setSelected(false);
        txtprojeto.setText("");
        txtvalorprojeto.setText("");
        txtdescricaoprojeto.setText("");
        txtnome.requestFocus();
        rativo.isSelected();
        //habilitando os campos e os botoes
        txtnome.setEnabled(true);
        spinidade.setEnabled(true);
        txtcpf.setEnabled(true);
        txttelefone.setEnabled(true);
        rativo.setEnabled(true);
        rinativo.setEnabled(true);
        txtprojeto.setEnabled(true);
        txtvalorprojeto.setEnabled(true);
        txtdescricaoprojeto.setEnabled(true); 
        btsalvar.setEnabled(true);
        btnovo.setEnabled(false);
        
        //atualizando tabela
        mostrarcliente();
        //variavel auxiliar receve o valor 0 referente ao novo
        auxiliar=0;
        aux_limp=0;
    }//GEN-LAST:event_btnovoActionPerformed

    private void dadospessoaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dadospessoaisMouseClicked
        if(aux_limp==1){
            //limpando os campos 
            txtnome.setText("");
            spinidade.setValue(0);
            txtcpf.setText("");
            txttelefone.setText("");
            rativo.setSelected(false);
            rinativo.setSelected(false);
            txtprojeto.setText("");
            txtvalorprojeto.setText("");
            txtdescricaoprojeto.setText("");  
        }
        //habilitando o botão novo e desabilitando os outros
        btnovo.setEnabled(true);
        bteditar.setEnabled(false);
        btexcluir.setEnabled(false);
        
        btnovo.requestFocus();
    }//GEN-LAST:event_dadospessoaisMouseClicked

    private void tblclienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblclienteMouseExited
        tblcliente.setEnabled(false);
    }//GEN-LAST:event_tblclienteMouseExited

    private void dadosprojetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dadosprojetoMouseClicked
        if(aux_limp==1){
            //limpando os campos 
            txtnome.setText("");
            spinidade.setValue(0);
            txtcpf.setText("");
            txttelefone.setText("");
            rativo.setSelected(false);
            rinativo.setSelected(false);
            txtprojeto.setText("");
            txtvalorprojeto.setText("");
            txtdescricaoprojeto.setText("");  
        }
        //habilitando o botão novo e desabilitando os outros
        btnovo.setEnabled(true);
        bteditar.setEnabled(false);
        btexcluir.setEnabled(false);
        
        btnovo.requestFocus();
    }//GEN-LAST:event_dadosprojetoMouseClicked

    private void tblclienteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblclienteMouseMoved
        tblcliente.setEnabled(true);
    }//GEN-LAST:event_tblclienteMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bteditar;
    private javax.swing.JButton btexcluir;
    private javax.swing.JButton btlimpar3;
    private javax.swing.JButton btnovo;
    private javax.swing.JButton btsalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel dadospessoais;
    private javax.swing.JPanel dadosprojeto;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rativo;
    private javax.swing.JRadioButton rinativo;
    private javax.swing.JSpinner spinidade;
    private javax.swing.JTable tblcliente;
    private javax.swing.JTextField txtcpf;
    private javax.swing.JTextArea txtdescricaoprojeto;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtprojeto;
    private javax.swing.JTextField txttelefone;
    private javax.swing.JTextField txtvalorprojeto;
    // End of variables declaration//GEN-END:variables
}
